### ISSUE TITLE
Build error MBP 2018

### ISSUE THREAD

**Issue by KlosStepan** [e2b-dev/e2b#59] opened 2023-07-02 17:29 UTC
I cloned and tried to start the project on my computer.
```zsh
➜  projects git clone https://github.com/e2b-dev/e2b
Cloning into 'e2b'...
remote: Enumerating objects: 12039, done.
remote: Counting objects: 100% (1218/1218), done.
remote: Compressing objects: 100% (386/386), done.
remote: Total 12039 (delta 871), reused 1009 (delta 818), pack-reused 10821
Receiving objects: 100% (12039/12039), 43.44 MiB | 16.75 MiB/s, done.
Resolving deltas: 100% (8167/8167), done.
➜  projects cd e2b
➜  e2b git:(main) npm start

> e2b@0.2.0 start /Users/stepo/projects/e2b
> docker compose build && (npm run db:reset || cd . && npm run db:start && docker compose up)

[+] Building 144.5s (27/38)
 => [e2b/api:latest internal] load build definition from Dockerfile     0.6s
 => => transferring dockerfile: 1.21kB                                  0.1s
 => [e2b/app:latest internal] load build definition from Dockerfile     1.0s
 => => transferring dockerfile: 1.04kB                                  0.0s
 => [e2b/api:latest internal] load .dockerignore                        0.6s
 => => transferring context: 186B                                       0.0s
 => [e2b/app:latest internal] load .dockerignore                        0.7s
 => => transferring context: 389B                                       0.0s
 => [e2b/api:latest internal] load metadata for docker.io/nikolaik/pyt  2.0s
 => [e2b/app:latest internal] load metadata for docker.io/library/node  1.8s
 => [e2b/app:latest internal] load build context                        0.5s
 => => transferring context: 1.25MB                                     0.3s
 => [e2b/app:latest runner 1/5] FROM docker.io/library/node:lts-slim@  27.4s
 => => resolve docker.io/library/node:lts-slim@sha256:77618f025144304c  0.0s
 => => sha256:77618f025144304c1e678fe27b3d67072da8ace6 1.21kB / 1.21kB  0.0s
 => => sha256:a555bf35be0a0fdc9d4ef8218b7bbeb05397a498 1.37kB / 1.37kB  0.0s
 => => sha256:47ca254e63dac631ffa3e92d51feb5d16e3fa477 7.01kB / 7.01kB  0.0s
 => => sha256:5b5fe70539cd6989aa19f25826309f9715a948 29.12MB / 29.12MB  6.6s
 => => sha256:b6b4ba8b66ef938dd20faab2757750e25471dfc6 3.35kB / 3.35kB  0.6s
 => => sha256:7164ad7f664d1f7a4fefd5edc6593037851ab9 45.99MB / 45.99MB  9.8s
 => => sha256:4aeac8a60b3be152c11cf56047295f20b19f35c4 2.74MB / 2.74MB  2.1s
 => => sha256:50cd09dcd0ffe4eebed48019bc297a4b651aedc256d1 448B / 448B  2.4s
 => => extracting sha256:5b5fe70539cd6989aa19f25826309f9715a9489cf1c05  3.7s
 => => extracting sha256:b6b4ba8b66ef938dd20faab2757750e25471dfc664924  0.0s
 => => extracting sha256:7164ad7f664d1f7a4fefd5edc6593037851ab996515c  12.7s
 => => extracting sha256:4aeac8a60b3be152c11cf56047295f20b19f35c4646ae  0.5s
 => => extracting sha256:50cd09dcd0ffe4eebed48019bc297a4b651aedc256d10  0.0s
 => [e2b/api:latest stage-1  1/12] FROM docker.io/nikolaik/python-nod  49.5s
 => => resolve docker.io/nikolaik/python-nodejs:python3.10-nodejs18-sl  0.1s
 => => sha256:5b5fe70539cd6989aa19f25826309f9715a948 29.12MB / 29.12MB  6.4s
 => => sha256:e0d8d1d843a38c15dfff43d7ed49a026aaddf62e 1.63kB / 1.63kB  0.0s
 => => sha256:f4c2cb1de449ee6c658d1035cd8cc93aa485fb47 8.95kB / 8.95kB  0.0s
 => => sha256:5e3d92572cc1017d354a178c0de533cbb05b414c 1.61kB / 1.61kB  0.0s
 => => sha256:f4b0e4004dc04711a8993bf16c12de46a97fb445 3.50MB / 3.50MB  3.3s
 => => sha256:c5424f0ac885ec615efbbae35449ca925b901c 17.43MB / 17.43MB  7.6s
 => => sha256:9d21fe1624ec14a17704060db0113fad2195119f1d4a 244B / 244B  7.7s
 => => sha256:de0194aa1c2187a0cf3ac9af8347bf734597fc25 3.37MB / 3.37MB  9.7s
 => => extracting sha256:5b5fe70539cd6989aa19f25826309f9715a9489cf1c05  3.7s
 => => sha256:6ebdd436fb631389bf78d63bf7458ef4503 123.86MB / 123.86MB  21.7s
 => => sha256:99b418d33008c6f307dbd7d5722201d2eb30500 3.31kB / 3.31kB  10.1s
 => => extracting sha256:f4b0e4004dc04711a8993bf16c12de46a97fb4451c82e  0.9s
 => => extracting sha256:c5424f0ac885ec615efbbae35449ca925b901ca2b5803  3.8s
 => => extracting sha256:9d21fe1624ec14a17704060db0113fad2195119f1d4a9  0.0s
 => => extracting sha256:de0194aa1c2187a0cf3ac9af8347bf734597fc253d3de  3.8s
 => => extracting sha256:99b418d33008c6f307dbd7d5722201d2eb30500bee385  0.0s
 => => extracting sha256:6ebdd436fb631389bf78d63bf7458ef45033c38dbf4e  22.0s
 => [e2b/api:latest internal] load build context                        0.4s
 => => transferring context: 673.12kB                                   0.3s
 => [e2b/api:latest playground 2/9] WORKDIR /playground                12.6s
 => [e2b/app:latest runner 2/5] WORKDIR /app                           12.6s
 => [e2b/api:latest playground 3/9] COPY playground/package.json playg  0.4s
 => [e2b/app:latest builder 3/7] COPY package.json package-lock.json*   0.4s
 => [e2b/api:latest playground 4/9] RUN npm ci                         80.8s
 => [e2b/app:latest builder 4/7] COPY prisma/schema.prisma ./prisma/sc  0.2s
 => CANCELED [e2b/app:latest builder 5/7] RUN npm ci                  100.0s
 => [e2b/api:latest stage-1  2/12] RUN poetry config virtualenvs.in-pr  4.0s
 => [e2b/api:latest stage-1  3/12] WORKDIR /app                         0.1s
 => [e2b/api:latest stage-1  4/12] COPY pyproject.toml poetry.lock ./   0.1s
 => [e2b/api:latest stage-1  5/12] RUN --mount=type=cache,target=/hom  52.8s
 => ERROR [e2b/api:latest stage-1  6/12] RUN poetry run opentelemetry  31.8s
 => [e2b/api:latest playground 5/9] COPY playground/tsconfig.json ./    0.1s
 => [e2b/api:latest playground 6/9] COPY playground/tsoa.json ./        0.1s
 => [e2b/api:latest playground 7/9] COPY playground/scripts/build.js .  0.1s
 => [e2b/api:latest playground 8/9] COPY playground/src ./src           0.1s
 => [e2b/api:latest playground 9/9] RUN npm run build                   2.3s
------
 > [e2b/api:latest stage-1  6/12] RUN poetry run opentelemetry-bootstrap -a install:
#24 3.248 instrumentation for package httpx<=0.23.0,>=0.18.0 is available but version httpx==0.23.3 is installed. Skipping.
#24 3.526 instrumentation for package starlette~=0.13.0 is available but version starlette==0.27.0 is installed. Skipping.
#24 7.510 Collecting opentelemetry-instrumentation-aws-lambda==0.39b0
#24 7.732   Downloading opentelemetry_instrumentation_aws_lambda-0.39b0-py3-none-any.whl (11 kB)
#24 7.756 Requirement already satisfied: opentelemetry-instrumentation==0.39b0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation-aws-lambda==0.39b0) (0.39b0)
#24 7.924 Collecting opentelemetry-propagator-aws-xray==1.0.1 (from opentelemetry-instrumentation-aws-lambda==0.39b0)
#24 7.965   Downloading opentelemetry_propagator_aws_xray-1.0.1-py3-none-any.whl (10 kB)
#24 7.979 Requirement already satisfied: opentelemetry-semantic-conventions==0.39b0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation-aws-lambda==0.39b0) (0.39b0)
#24 7.999 Requirement already satisfied: opentelemetry-api~=1.4 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation==0.39b0->opentelemetry-instrumentation-aws-lambda==0.39b0) (1.18.0)
#24 8.002 Requirement already satisfied: setuptools>=16.0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation==0.39b0->opentelemetry-instrumentation-aws-lambda==0.39b0) (67.8.0)
#24 8.004 Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation==0.39b0->opentelemetry-instrumentation-aws-lambda==0.39b0) (1.15.0)
#24 8.022 Requirement already satisfied: deprecated>=1.2.6 in ./.venv/lib/python3.10/site-packages (from opentelemetry-api~=1.4->opentelemetry-instrumentation==0.39b0->opentelemetry-instrumentation-aws-lambda==0.39b0) (1.2.14)
#24 8.024 Requirement already satisfied: importlib-metadata~=6.0.0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-api~=1.4->opentelemetry-instrumentation==0.39b0->opentelemetry-instrumentation-aws-lambda==0.39b0) (6.0.1)
#24 8.236 Requirement already satisfied: zipp>=0.5 in ./.venv/lib/python3.10/site-packages (from importlib-metadata~=6.0.0->opentelemetry-api~=1.4->opentelemetry-instrumentation==0.39b0->opentelemetry-instrumentation-aws-lambda==0.39b0) (3.15.0)
#24 9.573 Installing collected packages: opentelemetry-propagator-aws-xray, opentelemetry-instrumentation-aws-lambda
#24 9.783 Successfully installed opentelemetry-instrumentation-aws-lambda-0.39b0 opentelemetry-propagator-aws-xray-1.0.1
#24 11.28 Collecting opentelemetry-instrumentation-dbapi==0.39b0
#24 11.50   Downloading opentelemetry_instrumentation_dbapi-0.39b0-py3-none-any.whl (10 kB)
#24 11.58 Requirement already satisfied: opentelemetry-api~=1.12 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation-dbapi==0.39b0) (1.18.0)
#24 11.58 Requirement already satisfied: opentelemetry-instrumentation==0.39b0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation-dbapi==0.39b0) (0.39b0)
#24 11.59 Requirement already satisfied: opentelemetry-semantic-conventions==0.39b0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation-dbapi==0.39b0) (0.39b0)
#24 11.60 Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation-dbapi==0.39b0) (1.15.0)
#24 11.62 Requirement already satisfied: setuptools>=16.0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation==0.39b0->opentelemetry-instrumentation-dbapi==0.39b0) (67.8.0)
#24 11.65 Requirement already satisfied: deprecated>=1.2.6 in ./.venv/lib/python3.10/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-dbapi==0.39b0) (1.2.14)
#24 11.65 Requirement already satisfied: importlib-metadata~=6.0.0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-dbapi==0.39b0) (6.0.1)
#24 11.82 Requirement already satisfied: zipp>=0.5 in ./.venv/lib/python3.10/site-packages (from importlib-metadata~=6.0.0->opentelemetry-api~=1.12->opentelemetry-instrumentation-dbapi==0.39b0) (3.15.0)
#24 13.30 Installing collected packages: opentelemetry-instrumentation-dbapi
#24 13.42 Successfully installed opentelemetry-instrumentation-dbapi-0.39b0
#24 15.23 Collecting opentelemetry-instrumentation-logging==0.39b0
#24 15.42   Downloading opentelemetry_instrumentation_logging-0.39b0-py2.py3-none-any.whl (12 kB)
#24 15.44 Requirement already satisfied: opentelemetry-api~=1.12 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation-logging==0.39b0) (1.18.0)
#24 15.44 Requirement already satisfied: opentelemetry-instrumentation==0.39b0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation-logging==0.39b0) (0.39b0)
#24 15.45 Requirement already satisfied: setuptools>=16.0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation==0.39b0->opentelemetry-instrumentation-logging==0.39b0) (67.8.0)
#24 15.45 Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation==0.39b0->opentelemetry-instrumentation-logging==0.39b0) (1.15.0)
#24 15.47 Requirement already satisfied: deprecated>=1.2.6 in ./.venv/lib/python3.10/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-logging==0.39b0) (1.2.14)
#24 15.47 Requirement already satisfied: importlib-metadata~=6.0.0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-logging==0.39b0) (6.0.1)
#24 15.57 Requirement already satisfied: zipp>=0.5 in ./.venv/lib/python3.10/site-packages (from importlib-metadata~=6.0.0->opentelemetry-api~=1.12->opentelemetry-instrumentation-logging==0.39b0) (3.15.0)
#24 16.87 Installing collected packages: opentelemetry-instrumentation-logging
#24 16.93 Successfully installed opentelemetry-instrumentation-logging-0.39b0
#24 18.59 Collecting opentelemetry-instrumentation-sqlite3==0.39b0
#24 18.79   Downloading opentelemetry_instrumentation_sqlite3-0.39b0-py3-none-any.whl (8.7 kB)
#24 18.83 Requirement already satisfied: opentelemetry-api~=1.12 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation-sqlite3==0.39b0) (1.18.0)
#24 18.83 Requirement already satisfied: opentelemetry-instrumentation-dbapi==0.39b0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation-sqlite3==0.39b0) (0.39b0)
#24 18.84 Requirement already satisfied: opentelemetry-instrumentation==0.39b0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation-sqlite3==0.39b0) (0.39b0)
#24 18.87 Requirement already satisfied: setuptools>=16.0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation==0.39b0->opentelemetry-instrumentation-sqlite3==0.39b0) (67.8.0)
#24 18.88 Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation==0.39b0->opentelemetry-instrumentation-sqlite3==0.39b0) (1.15.0)
#24 18.90 Requirement already satisfied: opentelemetry-semantic-conventions==0.39b0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation-dbapi==0.39b0->opentelemetry-instrumentation-sqlite3==0.39b0) (0.39b0)
#24 18.92 Requirement already satisfied: deprecated>=1.2.6 in ./.venv/lib/python3.10/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-sqlite3==0.39b0) (1.2.14)
#24 18.92 Requirement already satisfied: importlib-metadata~=6.0.0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-sqlite3==0.39b0) (6.0.1)
#24 19.03 Requirement already satisfied: zipp>=0.5 in ./.venv/lib/python3.10/site-packages (from importlib-metadata~=6.0.0->opentelemetry-api~=1.12->opentelemetry-instrumentation-sqlite3==0.39b0) (3.15.0)
#24 20.28 Installing collected packages: opentelemetry-instrumentation-sqlite3
#24 20.35 Successfully installed opentelemetry-instrumentation-sqlite3-0.39b0
#24 21.65 Collecting opentelemetry-instrumentation-urllib==0.39b0
#24 21.82   Downloading opentelemetry_instrumentation_urllib-0.39b0-py3-none-any.whl (11 kB)
#24 21.88 Requirement already satisfied: opentelemetry-api~=1.12 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation-urllib==0.39b0) (1.18.0)
#24 21.90 Requirement already satisfied: opentelemetry-instrumentation==0.39b0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation-urllib==0.39b0) (0.39b0)
#24 21.91 Requirement already satisfied: opentelemetry-semantic-conventions==0.39b0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation-urllib==0.39b0) (0.39b0)
#24 22.12 Collecting opentelemetry-util-http==0.39b0 (from opentelemetry-instrumentation-urllib==0.39b0)
#24 22.15   Downloading opentelemetry_util_http-0.39b0-py3-none-any.whl (6.7 kB)
#24 22.16 Requirement already satisfied: setuptools>=16.0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation==0.39b0->opentelemetry-instrumentation-urllib==0.39b0) (67.8.0)
#24 22.16 Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation==0.39b0->opentelemetry-instrumentation-urllib==0.39b0) (1.15.0)
#24 22.18 Requirement already satisfied: deprecated>=1.2.6 in ./.venv/lib/python3.10/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-urllib==0.39b0) (1.2.14)
#24 22.18 Requirement already satisfied: importlib-metadata~=6.0.0 in ./.venv/lib/python3.10/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-urllib==0.39b0) (6.0.1)
#24 22.25 Requirement already satisfied: zipp>=0.5 in ./.venv/lib/python3.10/site-packages (from importlib-metadata~=6.0.0->opentelemetry-api~=1.12->opentelemetry-instrumentation-urllib==0.39b0) (3.15.0)
#24 23.43 Installing collected packages: opentelemetry-util-http, opentelemetry-instrumentation-urllib
#24 29.49 ERROR: Could not install packages due to an OSError: [Errno 5] Input/output error
#24 29.49
#24 29.70 Traceback (most recent call last):
#24 29.70   File "/app/.venv/lib/python3.10/site-packages/opentelemetry/instrumentation/bootstrap.py", line 37, in wrapper
#24 29.70     return func(package)
#24 29.70   File "/app/.venv/lib/python3.10/site-packages/opentelemetry/instrumentation/bootstrap.py", line 53, in _sys_pip_install
#24 29.70     subprocess.check_call(
#24 29.70   File "/usr/local/lib/python3.10/subprocess.py", line 369, in check_call
#24 29.70     raise CalledProcessError(retcode, cmd)
#24 29.70 subprocess.CalledProcessError: Command '['/app/.venv/bin/python', '-m', 'pip', 'install', '-U', '--upgrade-strategy', 'only-if-needed', 'opentelemetry-instrumentation-urllib==0.39b0']' returned non-zero exit status 1.
#24 29.70
#24 29.70 During handling of the above exception, another exception occurred:
#24 29.70
#24 29.70 Traceback (most recent call last):
#24 29.70   File "/app/.venv/bin/opentelemetry-bootstrap", line 8, in <module>
#24 29.70     sys.exit(run())
#24 29.70   File "/app/.venv/lib/python3.10/site-packages/opentelemetry/instrumentation/bootstrap.py", line 161, in run
#24 29.70     cmd()
#24 29.70   File "/app/.venv/lib/python3.10/site-packages/opentelemetry/instrumentation/bootstrap.py", line 123, in _run_install
#24 29.70     _sys_pip_install(lib)
#24 29.70   File "/app/.venv/lib/python3.10/site-packages/opentelemetry/instrumentation/bootstrap.py", line 45, in wrapper
#24 29.70     raise RuntimeError(msg)
#24 29.70 RuntimeError: Error calling system command "/app/.venv/bin/python -m pip install -U --upgrade-strategy only-if-needed opentelemetry-instrumentation-urllib==0.39b0" for package "opentelemetry-instrumentation-urllib==0.39b0"
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c poetry run opentelemetry-bootstrap -a install]: exit code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 17
npm ERR! e2b@0.2.0 start: `docker compose build && (npm run db:reset || cd . && npm run db:start && docker compose up)`
npm ERR! Exit status 17
npm ERR!
npm ERR! Failed at the e2b@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stepo/.npm/_logs/2023-07-02T17_21_24_436Z-debug.log
```
Log of the incident in .npm/logs folder.
```zsh
➜  _logs cat 2023-07-02T17_21_24_436Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/20.3.0_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v20.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle e2b@0.2.0~prestart: e2b@0.2.0
6 info lifecycle e2b@0.2.0~start: e2b@0.2.0
7 verbose lifecycle e2b@0.2.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle e2b@0.2.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/stepo/projects/e2b/node_modules/.bin:/Users/stepo/.pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/stepo/.local/bin:/Users/stepo/Library/Python/3.7/bin:/usr/local/texlive/2020/bin/x86_64-darwin:/Library/TeX/texbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
9 verbose lifecycle e2b@0.2.0~start: CWD: /Users/stepo/projects/e2b
10 silly lifecycle e2b@0.2.0~start: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'docker compose build && (npm run db:reset || cd . && npm run db:start && docker compose up)'
10 silly lifecycle ]
11 silly lifecycle e2b@0.2.0~start: Returned: code: 17  signal: null
12 info lifecycle e2b@0.2.0~start: Failed to exec start script
13 verbose stack Error: e2b@0.2.0 start: `docker compose build && (npm run db:reset || cd . && npm run db:start && docker compose up)`
13 verbose stack Exit status 17
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (node:events:511:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (node:events:511:28)
13 verbose stack     at maybeClose (node:internal/child_process:1098:16)
13 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
14 verbose pkgid e2b@0.2.0
15 verbose cwd /Users/stepo/projects/e2b
16 verbose Darwin 20.6.0
17 verbose argv "/usr/local/Cellar/node/20.3.0_1/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v20.3.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 17
22 error e2b@0.2.0 start: `docker compose build && (npm run db:reset || cd . && npm run db:start && docker compose up)`
22 error Exit status 17
23 error Failed at the e2b@0.2.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 17, true ]
```
**Describe the bug**
Build error

**To Reproduce**
1. git clone
2. npm start

Computer: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
2,3 GHz Čtyřjádrový Intel Core i5
16 GB 2133 MHz LPDDR3
Intel Iris Plus Graphics 655 1536 MB

**Comment by KlosStepan** [comment] 2023-07-02 17:42
Full storage on computer..

**Comment by KlosStepan** [comment] 2023-07-02 18:02
Seems like the storage is not the issue, same problem.
![Snímek obrazovky 2023-07-02 v 20 02 17](https://github.com/e2b-dev/e2b/assets/4312354/2bd61e65-c996-4b1b-b078-baed1a97d0ab)

**Comment by mlejva** [comment] 2023-07-02 18:31
Hey, thank you for reporting. The actual error seems to be this
```
Error calling system command "/app/.venv/bin/python -m pip install -U --upgrade-strategy only-if-needed opentelemetry-instrumentation-urllib==0.39b0" for package "opentelemetry-instrumentation-urllib==0.39b0"
```

**Comment by ValentaTomas** [comment] 2023-07-03 21:52
I cannot reproduce this exact problem on Ubuntu 22.04.2 or MBP M1 13.3.1 — if you get more info about this please share it here!

**Comment by ValentaTomas** [comment] 2023-08-25 10:48
I'm closing this - we are no longer using Docker for local development. Still, thanks for the original report!

**Closed by ValentaTomas** 2023-08-25 10:48 UTC
Labels: bug
